language: php
php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6

fast_finish: true

bin-dir: vendor/bin/

before_script:
- composer install -o -n

script:
  - vendor/bin/phpunit --testdox --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
