language: php
php:
  - 7.4
  - 8.0
  - 8.1
  - 8.2
  - 8.3

fast_finish: true

bin-dir: vendor/bin/

before_script:
- composer install -o -n

script:
  - vendor/bin/phpunit --testdox --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
